#!/bin/sh
#
# Show splash screen
#

FBV_ARGS="-d 15"
SPLASH_IMAGES="/root/splash.png"

start() {
	printf "Starting splash screen: "
	start-stop-daemon -b -S -q -m -p /var/run/splash.pid --exec /usr/bin/fbv -- $FBV_ARGS $SPLASH_IMAGES
	echo "OK"
}

stop() {
	printf "Stopping splash screen: "
	start-stop-daemon -K -q -p /var/run/splash.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
